In [12]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

In [13]:
source = requests.get('https://www.cbssports.com/nfl/draft/news/undrafted-free-agent-tracker-2020-rookie-signings-from-all-32-nfl-teams-in-one-spot-following-nfl-draft/').text

In [14]:
colNames = ['Division','Team','Player Info']
undraftedPlayers = pd.DataFrame(columns=colNames)

In [15]:
soup = BeautifulSoup(source, 'lxml')
main = soup.find('div', {"id": "article-main-body"})
teams = main.find('div', class_ = 'row')

In [16]:
for header in teams.find_all('h2'):
    # division name 
    divisionNameString = header.text
    for elem in header.next_siblings:
        if (elem.name == 'p'):
            teamName = elem
            # team name 
            teamNameString = teamName.text
            playerListUL = elem.find_next_sibling('ul')
            for player in playerListUL.find_all('li'):
                # player name 
                playerInfoString = player.text
                # this is where I add all the vriables into the data frame 
                playerList = [divisionNameString, teamNameString, playerInfoString]
                addOn = dict(zip(undraftedPlayers.columns, playerList))
                undraftedPlayers = undraftedPlayers.append(addOn, ignore_index=True)
        if (elem.name == 'h2'):
            break

In [17]:
undraftedPlayers.head(5)

     Division            Team                    Player Info
0   AFC East   Buffalo Bills      Reggie Gilliam, FB, Toledo
1   AFC East   Buffalo Bills              Ike Brown, CB, FIU
2   AFC East   Buffalo Bills      Trey Adams, OL, Washington
3   AFC East   Buffalo Bills   Garrett Taylor, S, Penn State
4   AFC East   Buffalo Bills     Marquel Harrell, OL, Auburn

In [18]:
#undraftedPlayers['Name2'] = undraftedPlayers['Player Info'].str.split(",",expand=True)[0]
# Best way to do it:
undraftedPlayers[['Name','Position', 'School']] = undraftedPlayers['Player Info'].str.split(",",expand=True)
undraftedPlayers['Name'] = undraftedPlayers['Name'].str.strip()
undraftedPlayers['Position'] = undraftedPlayers['Position'].str.strip()
undraftedPlayers['School'] = undraftedPlayers['School'].str.strip()

In [19]:
undraftedPlayers.drop('Player Info', axis = 1, inplace = True)

In [20]:
undraftedPlayers.head(5)

     Division            Team             Name Position      School
0   AFC East   Buffalo Bills    Reggie Gilliam       FB      Toledo
1   AFC East   Buffalo Bills         Ike Brown       CB         FIU
2   AFC East   Buffalo Bills        Trey Adams       OL  Washington
3   AFC East   Buffalo Bills    Garrett Taylor        S  Penn State
4   AFC East   Buffalo Bills   Marquel Harrell       OL      Auburn

In [21]:
undraftedPlayers.groupby('School').count().sort_values('Team', ascending=False).head(15)

                   Division  Team  Name  Position
School
Baylor                    9     9     9         9
Missouri                  7     7     7         7
Mississippi State         7     7     7         7
Georgia                   7     7     7         7
Washington                7     7     7         7
Auburn                    7     7     7         7
Wake Forest               6     6     6         6
Penn State                6     6     6         6
Michigan State            5     5     5         5
Notre Dame                5     5     5         5
Ohio State                5     5     5         5
Utah                      5     5     5         5
Iowa State                5     5     5         5
Arizona State             5     5     5         5
Fresno State              4     4     4         4

In [22]:
undraftedPlayers[undraftedPlayers.Position == 'QB']

,Division,Team,Name,Position,School
16,AFC East,New England Patriots,J'Mar Smith,QB,Louisiana Tech
35,AFC North,Baltimore Ravens,Tyler Huntley,QB,Utah
64,AFC North,Cleveland Browns,Kevin Davidson,QB,Princeton
134,AFC West,Denver Broncos,Riley Neal,QB,Vanderbilt
194,NFC East,New York Giants,Case Cookus,QB,Northern Arizona
219,NFC East,Philadelphia Eagles,Khalil Tate,QB,Arizona
221,NFC East,Washington Redskins,Steven Montez,QB,Colorado
308,NFC South,Tampa Bay Buccaneers,Reid Sinnett,QB,San Diego
341,NFC West,Los Angeles Rams,Bryce Perkins,QB,Virginia
342,NFC West,Los Angeles Rams,Josh Love,QB,San Jose State
360,NFC West,San Francisco 49ers,Broc Rutter,QB,North Central
365,NFC West,Seattle Seahawks,Anthony Gordon,QB,Washington State

In [23]:
undraftedPlayers.groupby('Team').count().sort_values('Division', ascending=False)

                       Division  Name  Position  School
Team
Baltimore Ravens             22    22        22      22
Arizona Cardinals            20    20        20      20
Los Angeles Chargers         20    20        19      19
Atlanta Falcons              19    19        19      19
Cleveland Browns             15    15        15      15
Jacksonville Jaguars         15    15        15      15
Philadelphia Eagles          13    13        13      13
Carolina Panthers            13    13        13      13
New York Giants              13    13        13      13
Tennessee Titans             13    13        13      13
Dallas Cowboys               13    13        13      13
Tampa Bay Buccaneers         13    13        13      13
Los Angeles Rams             13    13        13      13
Green Bay Packers            13    13        13      13
New Orleans Saints           13    13        13      13
Kansas City Chiefs           13    13        13      13
Seattle Seahawks             12    12        12      12
San Francisco 49ers          11    11        11      11
Minnesota Vikings            11    11        11      11
New England Patriots         10    10        10      10
Pittsburgh Steelers          10    10        10      10
New York Jets                 9     9         9       9
Indianapolis Colts            9     9         9       9
Miami Dolphins                8     8         8       8
Houston Texans                8     8         8       8
Chicago Bears                 8     8         8       8
Buffalo Bills                 8     8         8       8
Las Vegas Raiders             7     7         7       7
Detroit Lions                 7     7         7       7
Denver Broncos                7     7         7       7
Cincinnati Bengals            7     7         7       7
Washington Redskins           4     4         4       4

In [24]:
len(undraftedPlayers)

377